#!/usr/bin/env bash
# Build a self-contained Thunderbird profile for CI integration tests.
#
# Usage: scripts/ci/make-tb-profile.sh <profile-dir> [<xpi-path>]
#
# Sets up:
#  - One IMAP account "ci-test" pointing at localhost:3143 (greenmail default)
#  - One outgoing SMTP server on localhost:3025
#  - Our XPI pre-installed in the profile's extensions/ directory
#  - All the prefs that let an unsigned experiment-API extension run
#    (signature enforcement off, legacy + experiment flags on, first-run
#    wizards muted, background networking disabled so the offline CI doesn't
#    try to hit mail.mozilla.org)
#
# The TB profile format documentation is thin; these prefs were assembled
# from Mozilla's mailnews tests and the Thunderbird developer wiki, then
# trimmed to the minimum that boots an IMAP-accounted TB with our XPI
# loaded and the MCP server up.
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "usage: $0 <profile-dir> [<xpi-path>]" >&2
  exit 2
fi

PROFILE_DIR="$1"
XPI_PATH="${2:-dist/thunderbird-mcp.xpi}"
# Must match browser_specific_settings.gecko.id in extension/manifest.json
EXTENSION_ID="thunderbird-mcp@tkasperczyk.dev"

if [[ ! -f "$XPI_PATH" ]]; then
  echo "XPI not found at $XPI_PATH. Build it with: node scripts/build-xpi.cjs" >&2
  exit 1
fi

rm -rf "$PROFILE_DIR"
mkdir -p "$PROFILE_DIR/extensions"
mkdir -p "$PROFILE_DIR/ImapMail/localhost"

# Drop the XPI into the profile's extensions/ dir under its extension ID.
# TB discovers and installs it on first start when xpinstall.signatures.required
# is false. No interactive install prompt in headless mode.
cp "$XPI_PATH" "$PROFILE_DIR/extensions/${EXTENSION_ID}.xpi"

cat > "$PROFILE_DIR/prefs.js" <<'PREFS'
// Generated by scripts/ci/make-tb-profile.sh. Do not edit in place --
// regenerate from the script.

// ── Let our unsigned experiment-API XPI load ────────────────────────────
user_pref("xpinstall.signatures.required", false);
user_pref("extensions.legacy.enabled", true);
user_pref("extensions.experiments.enabled", true);
user_pref("extensions.autoDisableScopes", 0);
user_pref("extensions.enabledScopes", 15);

// ── First-run mutes ─────────────────────────────────────────────────────
user_pref("mail.provider.suppress_dialog_on_startup", true);
user_pref("mailnews.start_page.override_url", "");
user_pref("mailnews.start_page.url", "");
user_pref("app.update.enabled", false);
user_pref("app.update.auto", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.unified", false);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("network.proxy.type", 0);

// ── Account 1: IMAP → greenmail:3143, plain auth, no TLS ────────────────
user_pref("mail.account.account1.identities", "id1");
user_pref("mail.account.account1.server", "server1");
user_pref("mail.accountmanager.accounts", "account1");
user_pref("mail.accountmanager.defaultaccount", "account1");

user_pref("mail.identity.id1.useremail", "test@ci.local");
user_pref("mail.identity.id1.fullName", "CI Test");
user_pref("mail.identity.id1.smtpServer", "smtp1");
user_pref("mail.identity.id1.valid", true);

// ── Special folders for createDrafts / sendMail ───────────────────────
// Without explicit folder URIs, nsIMsgSend.createAndSendMessage in
// SaveAsDraft mode HANGS waiting for an unresolved drafts folder
// lookup -- the listener's onStopSending never fires and our 30 s
// smoke TIMEOUT trips before the 60 s internal timeout. Verified
// via the create_drafts trace dumping save.dispatch then no
// save.success / save.failed for 30 s.
//
// Pointing all four at the IMAP account's auto-created standard
// folders. Greenmail creates them lazily on first APPEND/SELECT.
user_pref("mail.identity.id1.drafts_folder",     "imap://test@ci.local@localhost/Drafts");
user_pref("mail.identity.id1.fcc_folder",        "imap://test@ci.local@localhost/Sent");
user_pref("mail.identity.id1.archive_folder",    "imap://test@ci.local@localhost/Archives");
user_pref("mail.identity.id1.stationery_folder", "imap://test@ci.local@localhost/Templates");

user_pref("mail.server.server1.type", "imap");
user_pref("mail.server.server1.hostname", "localhost");
user_pref("mail.server.server1.port", 3143);
user_pref("mail.server.server1.userName", "test@ci.local");
user_pref("mail.server.server1.realhostname", "localhost");
user_pref("mail.server.server1.realuserName", "test@ci.local");
user_pref("mail.server.server1.socketType", 0);           // plaintext, no TLS
// authMethod values (nsMsgAuthMethod.idl):
//   1 = none, 2 = old (bare IMAP4 LOGIN), 3 = passwordCleartext (AUTH=PLAIN/LOGIN),
//   4 = passwordEncrypted (CRAM-MD5), 5 = GSSAPI, 6 = NTLM, 7 = External,
//   8 = anySecure, 9 = any, 10 = OAuth2.
// Greenmail 2.1.2's IMAP CAPABILITY response is hardcoded to:
//   * CAPABILITY IMAP4rev1 LITERAL+ UIDPLUS SORT IDLE MOVE QUOTA
// Note the absence of AUTH=PLAIN / AUTH=LOGIN. TB 128 with authMethod=3
// waits to see one of those advertised and silently closes the session
// when none appears. authMethod=2 ("old") skips the AUTH= negotiation
// and sends the bare IMAP4 LOGIN command unconditionally, which
// greenmail handles fine.
user_pref("mail.server.server1.authMethod", 2);           // old-style LOGIN
user_pref("mail.server.server1.directory-rel", "[ProfD]ImapMail/localhost");
user_pref("mail.server.server1.login_at_startup", true);
user_pref("mail.server.server1.check_new_mail", false);   // manual IMAP fetch
user_pref("mail.server.server1.download_on_biff", false);
user_pref("mail.server.server1.offline_download", true);
user_pref("mail.server.server1.prettyName", "CI Test");
user_pref("mail.server.server1.name", "CI Test");

// ── SMTP: greenmail:3025 ────────────────────────────────────────────────
user_pref("mail.smtpservers", "smtp1");
user_pref("mail.smtp.defaultserver", "smtp1");
user_pref("mail.smtpserver.smtp1.hostname", "localhost");
user_pref("mail.smtpserver.smtp1.port", 3025);
user_pref("mail.smtpserver.smtp1.username", "test@ci.local");
user_pref("mail.smtpserver.smtp1.try_ssl", 0);            // plain

// ── Passwords: greenmail accepts any creds. We store it in plaintext
//    via the account manager pref so TB doesn't prompt in headless ─────
user_pref("signon.rememberSignons", true);
user_pref("signon.autologin.proxy", true);

// ── Calendar: start up quiet, no network calendars ─────────────────────
user_pref("calendar.timezone.useSystemTimezone", true);

// ── Offline/online behavior ────────────────────────────────────────────
user_pref("offline.autoDetect", false);
user_pref("network.online", true);

// ── Thunderbird MCP: expose every tool in CI ───────────────────────────
// The extension defaults DEFAULT_DISABLED_TOOLS (bulk_move_by_query,
// createDrafts, sendMail, deleteMessages, emptyTrash, ...) to hidden
// because they're destructive/irreversible and production users should
// opt in via the options page. In CI we are the user and we want the
// full API surface covered, so set the pref to the empty JSON array.
// prefHasUserValue flips to true, getDisabledTools() returns [], and
// tools/list advertises everything. UNDISABLEABLE_TOOLS still govern
// what can actually be called, and account-level access control still
// applies -- this only removes the safety hiding.
user_pref("extensions.thunderbird-mcp.disabledTools", "[]");

// ── CI-only credential injection for IMAP/SMTP ─────────────────────────
// Handed to api.js's CI login injector block. Cannot use logins.json
// directly: TB 128's LoginStore silently rejects plaintext (encType=0)
// entries, and we have no way to NSS-encrypt from a shell script.
// api.js calls nsILoginManager.addLogin with these entries at startup,
// TB does the NSS encryption, and subsequent IMAP login attempts find
// the stored credential instead of stalling 26s on a phantom UI prompt.
// Four entries for belt-and-suspenders URL matching (with and without
// port, for both IMAP and SMTP).
user_pref("extensions.thunderbird-mcp.ciInjectLogins", "[{\"origin\":\"imap://localhost\",\"httpRealm\":null,\"formActionOrigin\":null,\"username\":\"test@ci.local\",\"password\":\"test\"},{\"origin\":\"imap://localhost:3143\",\"httpRealm\":null,\"formActionOrigin\":null,\"username\":\"test@ci.local\",\"password\":\"test\"},{\"origin\":\"smtp://localhost\",\"httpRealm\":null,\"formActionOrigin\":null,\"username\":\"test@ci.local\",\"password\":\"test\"},{\"origin\":\"smtp://localhost:3025\",\"httpRealm\":null,\"formActionOrigin\":null,\"username\":\"test@ci.local\",\"password\":\"test\"}]");

// ── Enable dump() from chrome code ─────────────────────────────────────
// Without this pref, dump("...") from chrome JS (including our
// experiment API in api.js) is silently no-op'd in release builds.
// api.js's CI login injection uses dump() because console.info goes to
// the Browser Console which isn't captured as a CI artifact.
user_pref("browser.dom.window.dump.enabled", true);
user_pref("devtools.console.stdout.chrome", true);

// ── Defer IMAP login until something triggers it ───────────────────────
// With login_at_startup=true, TB tries to open an authenticated IMAP
// session before our extension has finished loading (and before it has
// had a chance to inject credentials). Setting this to false means the
// account is idle until the first URL submission (which, in the smoke
// test, comes well after the extension has populated the login
// manager), avoiding the startup race.
user_pref("mail.server.server1.login_at_startup", false);
PREFS

# Intentionally NOT writing logins.json here.
#
# TB 128's LoginStore (toolkit/components/passwordmgr/LoginStore.sys.mjs)
# expects on-disk entries with:
#   - `hostname`, `formSubmitURL` (legacy keys, still on-disk; the
#     `origin` / `formActionOrigin` rename was only applied to the
#     in-memory nsILoginInfo API)
#   - `encType: 1` with NSS-encrypted values in encryptedUsername /
#     encryptedPassword (encrypted with the profile's key4.db key)
#   - An example IMAP entry has `httpRealm` set to the server URI
# Source: https://renenyffenegger.ch/notes/Linux/fhs/home/username/
#         _thunderbird/abcd5678_default/logins_json
#
# Plaintext encType=0 simply doesn't work in TB 128, and NSS-encrypting
# from outside TB would require running the browser's own NSS tooling.
# Instead we let the extension itself inject credentials via
# nsILoginManager.addLogin() at startup (it already has chrome access),
# driven by extensions.thunderbird-mcp.ciInjectLogins below. TB handles
# the NSS encryption internally as part of addLogin(); no out-of-band
# tooling required.

# profiles.ini at the parent level so `thunderbird --profile <dir>` just works.
# Some TB versions require the explicit sentinel to accept an external profile.
touch "$PROFILE_DIR/times.json"
echo "{}" > "$PROFILE_DIR/times.json"

echo "TB profile ready at: $PROFILE_DIR"
echo "  XPI: $XPI_PATH (installed as $EXTENSION_ID)"
echo "  IMAP: localhost:3143 user=test@ci.local"
echo "  SMTP: localhost:3025 user=test@ci.local"
