#!/usr/bin/env bash
# Build a self-contained Thunderbird profile for CI integration tests.
#
# Usage: scripts/ci/make-tb-profile.sh <profile-dir> [<xpi-path>]
#
# Sets up:
#  - One IMAP account "ci-test" pointing at localhost:3143 (greenmail default)
#  - One outgoing SMTP server on localhost:3025
#  - Our XPI pre-installed in the profile's extensions/ directory
#  - All the prefs that let an unsigned experiment-API extension run
#    (signature enforcement off, legacy + experiment flags on, first-run
#    wizards muted, background networking disabled so the offline CI doesn't
#    try to hit mail.mozilla.org)
#
# The TB profile format documentation is thin; these prefs were assembled
# from Mozilla's mailnews tests and the Thunderbird developer wiki, then
# trimmed to the minimum that boots an IMAP-accounted TB with our XPI
# loaded and the MCP server up.
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "usage: $0 <profile-dir> [<xpi-path>]" >&2
  exit 2
fi

PROFILE_DIR="$1"
XPI_PATH="${2:-dist/thunderbird-mcp.xpi}"
# Must match browser_specific_settings.gecko.id in extension/manifest.json
EXTENSION_ID="thunderbird-mcp@tkasperczyk.dev"

if [[ ! -f "$XPI_PATH" ]]; then
  echo "XPI not found at $XPI_PATH. Build it with: node scripts/build-xpi.cjs" >&2
  exit 1
fi

rm -rf "$PROFILE_DIR"
mkdir -p "$PROFILE_DIR/extensions"
mkdir -p "$PROFILE_DIR/ImapMail/localhost"

# Drop the XPI into the profile's extensions/ dir under its extension ID.
# TB discovers and installs it on first start when xpinstall.signatures.required
# is false. No interactive install prompt in headless mode.
cp "$XPI_PATH" "$PROFILE_DIR/extensions/${EXTENSION_ID}.xpi"

cat > "$PROFILE_DIR/prefs.js" <<'PREFS'
// Generated by scripts/ci/make-tb-profile.sh. Do not edit in place --
// regenerate from the script.

// ── Let our unsigned experiment-API XPI load ────────────────────────────
user_pref("xpinstall.signatures.required", false);
user_pref("extensions.legacy.enabled", true);
user_pref("extensions.experiments.enabled", true);
user_pref("extensions.autoDisableScopes", 0);
user_pref("extensions.enabledScopes", 15);

// ── First-run mutes ─────────────────────────────────────────────────────
user_pref("mail.provider.suppress_dialog_on_startup", true);
user_pref("mailnews.start_page.override_url", "");
user_pref("mailnews.start_page.url", "");
user_pref("app.update.enabled", false);
user_pref("app.update.auto", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.unified", false);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("network.proxy.type", 0);

// ── Account 1: IMAP → greenmail:3143, plain auth, no TLS ────────────────
user_pref("mail.account.account1.identities", "id1");
user_pref("mail.account.account1.server", "server1");
user_pref("mail.accountmanager.accounts", "account1");
user_pref("mail.accountmanager.defaultaccount", "account1");

user_pref("mail.identity.id1.useremail", "test@ci.local");
user_pref("mail.identity.id1.fullName", "CI Test");
user_pref("mail.identity.id1.smtpServer", "smtp1");
user_pref("mail.identity.id1.valid", true);

user_pref("mail.server.server1.type", "imap");
user_pref("mail.server.server1.hostname", "localhost");
user_pref("mail.server.server1.port", 3143);
user_pref("mail.server.server1.userName", "test@ci.local");
user_pref("mail.server.server1.realhostname", "localhost");
user_pref("mail.server.server1.realuserName", "test@ci.local");
user_pref("mail.server.server1.socketType", 0);           // plaintext, no TLS
user_pref("mail.server.server1.authMethod", 3);           // plain password
user_pref("mail.server.server1.directory-rel", "[ProfD]ImapMail/localhost");
user_pref("mail.server.server1.login_at_startup", true);
user_pref("mail.server.server1.check_new_mail", false);   // manual IMAP fetch
user_pref("mail.server.server1.download_on_biff", false);
user_pref("mail.server.server1.offline_download", true);
user_pref("mail.server.server1.prettyName", "CI Test");
user_pref("mail.server.server1.name", "CI Test");

// ── SMTP: greenmail:3025 ────────────────────────────────────────────────
user_pref("mail.smtpservers", "smtp1");
user_pref("mail.smtp.defaultserver", "smtp1");
user_pref("mail.smtpserver.smtp1.hostname", "localhost");
user_pref("mail.smtpserver.smtp1.port", 3025);
user_pref("mail.smtpserver.smtp1.username", "test@ci.local");
user_pref("mail.smtpserver.smtp1.try_ssl", 0);            // plain

// ── Passwords: greenmail accepts any creds. We store it in plaintext
//    via the account manager pref so TB doesn't prompt in headless ─────
user_pref("signon.rememberSignons", true);
user_pref("signon.autologin.proxy", true);

// ── Calendar: start up quiet, no network calendars ─────────────────────
user_pref("calendar.timezone.useSystemTimezone", true);

// ── Offline/online behavior ────────────────────────────────────────────
user_pref("offline.autoDetect", false);
user_pref("network.online", true);
PREFS

# Passwords: TB reads logins from logins.json rather than prefs.js on
# modern versions. Pre-populate with greenmail's any-creds-accepted auth.
cat > "$PROFILE_DIR/logins.json" <<'LOGINS'
{
  "nextId": 3,
  "logins": [
    {
      "id": 1,
      "hostname": "imap://localhost",
      "httpRealm": null,
      "formSubmitURL": null,
      "usernameField": "",
      "passwordField": "",
      "encryptedUsername": "test@ci.local",
      "encryptedPassword": "test",
      "guid": "{00000000-0000-0000-0000-000000000001}",
      "encType": 0,
      "timeCreated": 0,
      "timeLastUsed": 0,
      "timePasswordChanged": 0,
      "timesUsed": 1
    },
    {
      "id": 2,
      "hostname": "smtp://localhost",
      "httpRealm": null,
      "formSubmitURL": null,
      "usernameField": "",
      "passwordField": "",
      "encryptedUsername": "test@ci.local",
      "encryptedPassword": "test",
      "guid": "{00000000-0000-0000-0000-000000000002}",
      "encType": 0,
      "timeCreated": 0,
      "timeLastUsed": 0,
      "timePasswordChanged": 0,
      "timesUsed": 1
    }
  ],
  "potentiallyVulnerablePasswords": [],
  "dismissedBreachAlertsByLoginGUID": {},
  "version": 3
}
LOGINS

# profiles.ini at the parent level so `thunderbird --profile <dir>` just works.
# Some TB versions require the explicit sentinel to accept an external profile.
touch "$PROFILE_DIR/times.json"
echo "{}" > "$PROFILE_DIR/times.json"

echo "TB profile ready at: $PROFILE_DIR"
echo "  XPI: $XPI_PATH (installed as $EXTENSION_ID)"
echo "  IMAP: localhost:3143 user=test@ci.local"
echo "  SMTP: localhost:3025 user=test@ci.local"
