// Auto-generated by scripts/build-xpi.cjs. Do not edit.
// Add tool files under lib/tools/ and rebuild -- the manifest picks
// them up via filesystem scan.
export const TOOL_MODULES = [
  "inbox-inventory.sys.mjs"
];
